### ISSUE TITLE
js: md docs 需要复用主页的样式并且修改 <title>

### ISSUE THREAD

**Issue by waylybaye** [waylybaye/opencat.app#11]

**Comment by asfman** [comment]
主页有啥样式？加个className={styles.container}吗？要不要引入tailwindcss，感觉现在主流都在用tailwindcss写页面。
修改 <title>是啥意思？

**Comment by waylybaye** [comment]
@asfman  现在 docs 不是没有任何样式吗，希望有个统一的 header 和 footer。可以引入啊，如果能找到个比较简约朴素的文档模板最好了。

现在的 md 的标题没有写到 <header><title/></head> 里。
