### ISSUE TITLE
md doc 支持图片

### ISSUE THREAD

**Issue by waylybaye** [waylybaye/opencat.app#18]

**Comment by asfman** [comment]
默认就是支持的吧？

**Comment by waylybaye** [comment]
本地图片好像不支持，在 docs 和 public 的图片文件夹都不显示。

**Comment by asfman** [comment]
> 本地图片好像不支持，在 docs 和 public 的图片文件夹都不显示。

public支持的，你访问路径用/xxx.png，nextjs静态图片都是放public目录的吧
