### ISSUE TITLE
增加多窗口模式

### ISSUE THREAD

**Issue by scomper** [waylybaye/opencat.app#2]
和 ChatGPT 交互过程中经常需要多线程并行，一个窗口作为主线索推进，另一个窗口会用来搜索关联信息；这样能避免跳跃性的提问让上下文失去有效关联，同时保持主题的清晰。

![CleanShot 2023-03-28 at 19 57 47@2x](https://user-images.githubusercontent.com/13041847/228240029-a703959f-d806-4950-a9fe-ede3e7a26952.png)

**Comment by waylybaye** [comment]
1.1.8(106)  已支持。
