### ISSUE TITLE
怎么一直显示无法连接服务器？

### ISSUE THREAD

**Issue by okaypan** [waylybaye/opencat.app#24]
<img width="537" alt="Screenshot 2023-04-19 at 19 38 08" src="https://user-images.githubusercontent.com/38337093/233063439-00e98311-920a-4485-922d-94eb44ed93f8.png">
在两台Mac电脑都有安装，设置完全一样，但是其中一台总显示无法连接服务器。请问怎么回事？
ps: 购买app是pro会员

**Comment by waylybaye** [comment]
1.1.17 有个 bug，可以在自定义域名里面暂时填入 api.openai.com 既可。已经修复此问题，下个版本马上更新。

**Comment by okaypan** [comment]
> 1.1.17 有个 bug，可以在自定义域名里面暂时填入 api.openai.com 既可。已经修复此问题，下个版本马上更新。

感谢回复。
还有个bug, menubar没有选casual chat，但是默认出现。

**Comment by okaypan** [comment]
@waylybaye 另外，希望增加一个语音调速的功能
