### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [waylybaye/opencat.app#30]
Is there any chance you could release a Linux build? 

I am currently mainly using Mint OS instead of working on my Mac but I am really missing OpenCat.

Much appreciate all your work!

**Comment by waylybaye** [comment]
Thank you for your suggestion. However, we currently do not have plans to accommodate Linux. We utilize native technology for our app development and would need to start from scratch to make it compatible with Linux.

**Comment by sanderDijkxhoorn** [comment]
Understandable, thanks for replying.
